name: gitleaks_scaner
on:
  push:
    branches: 
      - "main"
      - "apxitekt0r-patch-1"
      - "releases/**"
  pull_request:
    branches: 
      - "main"
      - "apxitekt0r-patch-1"
      - "releases/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
